feature/P2C-912- Implement order creation API
av-samoylov/pain-market1 pull request #3
Opened 2024-01-10 19:00 UTC by av-samoylov

Added classes Order, OrderController, OrderService, OrderRepository

2024-01-10 22:01 UTC, dobraccoon requested changes

2024-01-10 22:01 UTC, dobraccoon commented on src/main/java/ru/avsamoylov/painmarket1/repository/OrderRepository.java
> +                new Random().nextLong(), order.getProductId(),
форматирование, либо все параметры в строку, либо в 1 столбец

2024-01-10 22:01 UTC, dobraccoon commented on src/main/java/ru/avsamoylov/painmarket1/service/OrderService.java
> +    public Order createOrder(Order order) {
между полем и методом должна быть пустая строка

2024-01-11 08:32 UTC, av-samoylov commented on src/main/java/ru/avsamoylov/painmarket1/repository/OrderRepository.java
> +                new Random().nextLong(), order.getProductId(),
исправлено

2024-01-12 13:54 UTC, merged